"""
Part 2: train the policy network to replicate the simple behavior policy
(5 sensors, no other vehicles) using the provided data/test.txt.

Each row of test.txt is: action, x, y, vx, vy, s1, s2, s3, s4, s5
"action" was already generated by the simple behavior policy, so we can
train directly on it with supervised learning.
"""
import os
import numpy as np
from policy_network import PolicyNetwork
from behavior_policy import behavior_actions

ACTION_NAMES = {0: "turn left", 1: "turn right", 2: "speed up", 3: "no action"}


def load_data(path):
    """Each row is: action, x, y, vx, vy, s1, ..., sk.
    The network's input is only the sensors (s1..sk)."""
    data = np.loadtxt(path, delimiter=",", dtype=np.float64)
    y = data[:, 0].astype(int)
    X = data[:, 5:]  # sensors only
    return X, y


def main():
    root = os.path.dirname(os.path.abspath(__file__))
    X, y = load_data(os.path.join(root, "data", "test.txt"))
    k = X.shape[1]
    print(f"Loaded {len(X)} rows, k={k} sensors")

    # Sanity check: confirm the labels in test.txt really do match the
    # simple behavior policy rule.
    rule_labels = behavior_actions(X)
    match = np.mean(rule_labels == y) * 100.0
    print(f"Labels in test.txt match the behavior policy rule: {match:.1f}%")

    # Train/validation split (80/20), shuffled.
    rng = np.random.default_rng(42)
    idx = rng.permutation(len(X))
    X, y = X[idx], y[idx]
    n_train = int(0.8 * len(X))
    X_train, y_train = X[:n_train], y[:n_train]
    X_val, y_val = X[n_train:], y[n_train:]

    net = PolicyNetwork(k=k, hidden1=32, hidden2=32)

    print("\nBefore training:")
    print(f"  train_acc={net.accuracy(X_train, y_train):.2f}%  val_acc={net.accuracy(X_val, y_val):.2f}%")

    print("\nTraining...")
    net.train(X_train, y_train, epochs=300, batch_size=32, lr=0.1)

    print("\nAfter training:")
    print(f"  train_acc={net.accuracy(X_train, y_train):.2f}%  val_acc={net.accuracy(X_val, y_val):.2f}%")

    out_path = os.path.join(root, "answers", "part2_predictions.txt")
    predictions = net.predict(X_val)
    np.savetxt(out_path, predictions, fmt="%d")
    print(f"\nSaved validation predictions to {out_path}")


if __name__ == "__main__":
    main()
